# -*- coding: utf-8 -*-
"""Hackathon_test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FnAszrW5Q3Umr8PTJFT0TCd4waILnuQm
"""

import requests
from PIL import Image
from io import BytesIO
def predict_from_url(model, url, label_dict):
  response = requests.get(url)
  image = Image.open(BytesIO(response.content))
  image = image.resize((PIC_SIZE, PIC_SIZE))
  image_array = img_to_array(image)
  image_array = np.expand_dims(image_array, axis=0)
  image_array = preprocess_input(image_array)
  pred_vec = model.predict(image_array)
  pred_class = np.argmax(pred_vec)
  confidence = np.max(pred_vec)
  label = label_dict[pred_class]
  return label, confidence, pred_vec



img_path =  'https://media.npr.org/assets/img/2021/10/14/ap21287185717628-bc8f03d3cccf095a593efa95d04bc74fdf14fb77.jpg'
predict_from_url(mymodel, img_path, labels_dict)

